# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/travis/travis/docker-build
  - chmod +x docker-build
 
install:
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build meson

env:
  - DISTRO="base/archlinux"
  - DISTRO="debian:sid"
  - DISTRO="fedora:29"
  - DISTRO="ubuntu:18.10"

##########################################################3
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################3
requires:
  archlinux:
    - git
    - glib2
    - gobject-introspection
    - meson
    - vala
  debian:
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libx11-dev
    - meson
    - valac
  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/caja.git/
    # The above packages is installed by 'dnf groupinstall build'
    - gcc
    - git
    - vala-devel
    - gobject-introspection-devel
    - meson
    - ninja-build
    - gettext
    - redhat-rpm-config
  ubuntu:
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libx11-dev
    - meson
    - valac
variables:
    - CFLAGS="-Wall"
configures:
  meson:
    - --prefix /usr
    - -Denable_gtk_doc=true
    - -Dwith_introspection=true
    - -Dwith_vala=true
    - -Denable_tests=true
after_scripts:
  - cd ${BUILD_DIR}
  - ninja dist
