dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
    #- curl -L -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - curl -L -o docker-build https://github.com/yetist/mate-dev-scripts/raw/travis/travis/docker-build
  - chmod +x docker-build
 
install:
  - ./docker-build --name ${DISTRO} --verbose --install

script:
  - ./docker-build --name ${DISTRO} --verbose --build meson

env:
  - DISTRO="ubuntu:18.10"
    #- DISTRO="base/archlinux"
    #  - DISTRO="debian:sid"
    #  - DISTRO="fedora:29"
