dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
    #- curl -L -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - curl -L -o docker-build https://github.com/yetist/mate-dev-scripts/raw/travis/travis/docker-build
  - chmod +x docker-build
 
install:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build meson

env:
  - DISTRO="ubuntu:18.10"
    #- DISTRO="base/archlinux"
    #  - DISTRO="debian:sid"
    #  - DISTRO="fedora:29"

##########################################################3
# The follow lines is added for docker-build
##########################################################3
requires:
  ubuntu:
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libx11-dev
    - meson
    - valac
variables:
    - CFLAGS="-Wall"
configures:
  meson:
    - --prefix /usr
    - -Denable_gtk_doc=true
    - -Dwith_introspection=true
    - -Dwith_vala=true
    - -Denable_tests=true
after_scripts:
    - if [ "$BUILD_TYPE" = "meson" ]; then ninja dist; else make distcheck; fi
