/* liblunar-gtk.vapi generated by vapigen, do not modify. */

[CCode (cprefix = "Lunar", lower_case_cprefix = "lunar_")]
namespace Lunar {
	[CCode (cheader_filename = "lunar-gtk/lunar-calendar.h")]
	public class Calendar : Gtk.Calendar, Gtk.Buildable, Atk.Implementor {
		[CCode (type = "GtkWidget*", has_construct_function = false)]
		public Calendar ();
		public void set_jieri_color (Gdk.Color color);
	}
}
