#!/bin/sh

VERSION=$1

if [ ! -f lunar-date-$VERSION.tar.gz ]; then
	echo "ERROR: lunar-date-$VERSION.tar.gz does not exist..."
	exit 1
fi

echo ""

echo "Checking lunar-date-$VERSION.tar.gz..."
tar xfz lunar-date-$VERSION.tar.gz


for file in INSTALL NEWS README 
do
	echo -n "$file... "
	if [ "x`grep $VERSION lunar-date-$VERSION/$file | wc -l | awk -F' ' '{print $1}'`" = "x0" ]; then
		echo "failed."
		exit 1
	else
		echo "ok"
	fi
done

echo -n "INSTALL..."
if [ "x`grep $VERSION lunar-date-$VERSION/INSTALL | wc -l | awk -F' ' '{print $1}'`" = "x2" ]; then 
	echo "ok" 
else
	echo "failed."
	exit 1
fi

echo ""
echo "Number of lines in created documentation files:"

LC_ALL=C wc -l lunar-date-$VERSION/docs/reference/html/*.html | grep total 

rm -rf lunar-date-$VERSION
